#@ load("@ytt:data", "data")
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: postgres-where-for-dinner
  namespace: #@ data.values.workloadNamespace
spec:
  storageClassName: #@ data.values.storageClassName
  monitorStorageClassName: #@ data.values.storageClassName
  memory: 800Mi
  cpu: "0.8"
  storageSize: 800M
  highAvailability:
    enabled: false
  imagePullSecret:
    name: registries-credentials
