#@ load("@ytt:data", "data")
---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: redis-where-for-dinner-redis-password
  namespace: #@ data.values.workloadNamespace
spec:
  length: 64
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
---
apiVersion: v1
kind: Service
metadata:
  name: redis-where-for-dinner
  namespace: #@ data.values.workloadNamespace
  labels:
    app: where-for-dinner
    service: redis-where-for-dinner
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: where-for-dinner
    service: redis-where-for-dinner
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-where-for-dinner
  namespace: #@ data.values.workloadNamespace
  labels:
    app: where-for-dinner
    service: redis-where-for-dinner
spec:
  selector:
    matchLabels:
      app: where-for-dinner
      service: redis-where-for-dinner
  replicas: 1
  template:
    metadata:
      labels:
        app: where-for-dinner
        service: redis-where-for-dinner
    spec:
      containers:
      - name: redis
        image: bitnami/redis
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        env:
        - name: REDIS_HOST
          value: redis-where-for-dinner
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-where-for-dinner-redis-password
              key: password
        volumeMounts:
        - mountPath: /var/lib/redis
          name: redis-data

      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: where-for-dinner-bitnami-redis-secret-template-reader
  namespace: #@ data.values.workloadNamespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: where-for-dinner-bitnami-redis-secret-template-reader
  namespace: #@ data.values.workloadNamespace
rules:
- apiGroups:
  - '*'
  resources:
  - secrets
  - services
  - redis
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: where-for-dinner-bitnami-redis-secret-template-reader
  namespace: #@ data.values.workloadNamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: where-for-dinner-bitnami-redis-secret-template-reader
subjects:
- kind: ServiceAccount
  name: where-for-dinner-bitnami-redis-secret-template-reader
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: redis-where-for-dinner-redis-secret
  namespace: #@ data.values.workloadNamespace
spec:
  serviceAccountName: where-for-dinner-bitnami-redis-secret-template-reader
  inputResources:
  - name: redis-service
    ref:
      apiVersion: v1
      kind: Service
      name: redis-where-for-dinner
  - name: creds
    ref:
      apiVersion: v1
      kind: Secret
      name: redis-where-for-dinner-redis-password
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
        app.kubernetes.io/instance: redis-where-for-dinner
        services.apps.tanzu.vmware.com/class: where-for-dinner-bitnami-redis
    stringData:
      port: $(.redis-service.spec.ports[?(@.name=="redis")].port)
      host: #@ "redis-where-for-dinner." + data.values.workloadNamespace
      provider: bitnami
      type: redis
    data:
      password: $(.creds.data.password)
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: bitnami-redis-where-for-dinner
spec:
  description:
    short: Where For Dinner Bitnami Redis
  pool:
    kind: Secret
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: where-for-dinner-bitnami-redis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: where-for-dinner-bitnami-redis-secret-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch