#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-api-gateway
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
  resources:     
    requests:         
      memory: "1G"
      cpu: "100m"
    limits:         
      memory: "1.5G"
      cpu: "1000m" 
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-api-gateway
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-search
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  env:
  - name: spring_profiles_active
    value: #@ data.values.database
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: rmq
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: rmq-where-for-dinner
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.database + "-where-for-dinner"
  resources:     
    requests:         
      memory: "1G"
      cpu: "100m"
    limits:         
      memory: "1.5G"
      cpu: "1500m" 
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-search
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-search-proc
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-search-proc
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  build:
    env:
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: -P native -Dmaven.test.skip=true --no-transfer-progress package
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
  resources:     
    requests:         
      memory: "1G"
      cpu: "100m"
    limits:         
      memory: "1.5G"
      cpu: "1000m" 
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-search-proc
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-notify
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-notify
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  build:
    env:
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: -P native -Dmaven.test.skip=true --no-transfer-progress package
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
  resources:     
    requests:         
      memory: "1G"
      cpu: "100m"
    limits:         
      memory: "1.5G"
      cpu: "1000m" 
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-notify
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-availability
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-availability
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  build:
    env:
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: -P native -Dmaven.test.skip=true --no-transfer-progress package
  env:
  - name: spring_profiles_active
    value: #@ data.values.database
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
      autoscaling.knative.dev/minScale: "1"
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: #@ data.values.database + "-where-for-dinner"
  resources:     
    requests:         
      memory: "1G"
      cpu: "100m"
    limits:         
      memory: "1.5G"
      cpu: "1500m" 
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-availability
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner-ui
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-ui
    networking.knative.dev/visibility: cluster-local
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
      autoscaling.knative.dev/minScale: "1"
  resources:     
    requests:         
      memory: "1G"
      cpu: "100m"
    limits:         
      memory: "1.5G"
      cpu: "1000m" 
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-ui
