#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: where-for-dinner
  namespace: #@ data.values.workloadNamespace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: where-for-dinner-api-gateway
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
spec:
  params:
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: taplongevity
  - name: gitops_repository_name
    value: #@ data.values.gitopsRepositoryName
  - name: gitops_ssh_secret
    value: git-secret
  - name: gitops_server_kind
    value: github
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
      autoscaling.knative.dev/target: "200"
      autoscaling.knative.dev/maxScale: "4"
  resources:     
    requests:         
      memory: "500M"
      cpu: "100m"
    limits:         
      memory: "750M"
      cpu: "1000m" 
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"  
  source:
    git:
      url: #@ data.values.gitRepository
      ref:
        branch: main
    subPath: where-for-dinner-api-gateway
